# Generated by Django 5.1 on 2025-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='initiated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('IN', 'Initiated'), ('SH', 'Kit has shipped'), ('DO', 'Completed')], max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='project_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='redcap_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_nr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
