# Generated by Django 5.1 on 2025-01-21 21:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_remove_order_tracking_nr_order_tracking_nrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_tracking_nr',
        ),
        migrations.AddField(
            model_name='order',
            name='return_tracking_nrs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
