# Generated by Django 5.1 on 2025-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_remove_order_return_tracking_nr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redcap_log', models.TextField(blank=True, null=True)),
                ('gbf_log', models.TextField(blank=True, null=True)),
                ('apsscheduler_log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
