# Generated by Django 5.1 on 2025-01-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_rename_apsscheduler_log_orderlog_apsscheduler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='gbf_log',
            new_name='gbf',
        ),
    ]
