# Generated by Django 5.1 on 2025-01-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_alter_orderlog_apsscheduler_alter_orderlog_gbf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='apsscheduler',
            new_name='runapsscheduler',
        ),
    ]
