# Generated by Django 5.1 on 2025-01-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_rename_apsscheduler_orderlog_runapsscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='gbf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='redcap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='runapsscheduler',
            field=models.TextField(blank=True, null=True),
        ),
    ]
