# Generated by Django 5.1 on 2025-01-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_alter_orderlog_gbf_alter_orderlog_redcap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='runapsscheduler',
            new_name='runapscheduler',
        ),
    ]
