# Generated by Django 5.1 on 2025-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_rename_runapsscheduler_orderlog_runapscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='runapscheduler',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
