# Generated by Django 5.1 on 2025-01-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0017_alter_orderlog_gbf_alter_orderlog_redcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='order',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
