# Generated by Django 5.1 on 2025-01-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0019_rename_order_orderlog_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='runapscheduler',
            new_name='apscheduler',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
