# Generated by Django 5.1 on 2025-01-30 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_confirmationchecklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 48, 49, 978863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 48, 49, 978863, tzinfo=datetime.timezone.utc)),
        ),
    ]
