# Generated by Django 5.1 on 2025-01-31 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0022_alter_confirmationchecklog_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 22, 25, 21, 962604, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 22, 25, 21, 962604, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
