# Generated by Django 5.1 on 2025-02-03 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0023_confirmationchecklog_end_time_orderlog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 17, 4, 815323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 17, 4, 815323, tzinfo=datetime.timezone.utc)),
        ),
    ]
