# Generated by Django 5.1 on 2025-02-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_order_tube_serials'),
        ('track', '0030_alter_confirmationchecklog_end_time_and_more'),
    ]

    operations = [
    ]
