# Generated by Django 5.1 on 2025-02-05 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0031_merge_20250205_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='apscheduler',
        ),
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 22, 6, 43, 1823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 22, 6, 43, 1823, tzinfo=datetime.timezone.utc)),
        ),
    ]
