# Generated by Django 5.1 on 2025-02-24 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0034_alter_confirmationchecklog_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationchecklog',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 22, 18, 43, 234831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 22, 18, 43, 234831, tzinfo=datetime.timezone.utc)),
        ),
    ]
