# Generated by Django 5.1 on 2025-02-24 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0036_alter_confirmationchecklog_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationchecklog',
            name='is_error',
        ),
        migrations.RemoveField(
            model_name='orderlog',
            name='is_error',
        ),
        migrations.AddField(
            model_name='confirmationchecklog',
            name='is_error_thrown',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='is_error_thrown',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 23, 5, 46, 798938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 23, 5, 46, 798938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
    ]
