# Generated by Django 5.1 on 2025-02-24 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0037_remove_confirmationchecklog_is_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationchecklog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 23, 20, 7, 632920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 23, 20, 7, 632920, tzinfo=datetime.timezone.utc)),
        ),
    ]
